#!/bin/bash

SCRIPTS_DIR="$(dirname "$(readlink -f "${0}")")"

if [ "$(whoami)" != "root" ]; then
    echo "You have to run as Superuser!"
    exit 1
fi

if ! command -v wget &> /dev/null && ! command -v chmod &> /dev/null && ! command -v rm &> /dev/null; then
    echo "E: wget and chmod and rm is Missing"
    exit 1
else
    rm -rf "$SCRIPTS_DIR/UniversalCleanup" "$SCRIPTS_DIR/CleanRam"
    wget -q -O"$SCRIPTS_DIR/UniversalCleanup" https://raw.githubusercontent.com/MrR736/RootTools/refs/heads/main/UniversalCleanup
    chmod +x "$SCRIPTS_DIR/UniversalCleanup"
    wget -q -O"$SCRIPTS_DIR/CleanRam" https://raw.githubusercontent.com/MrR736/RootTools/refs/heads/main/CleanRam
    chmod +x "$SCRIPTS_DIR/CleanRam"
fi
