#!/bin/bash
## Bash Script to clear cached memory on (Ubuntu/Debian) Linux
## By Philipp Klaus
## see <http://blog.philippklaus.de/2011/02/clear-cached-memory-on-ubuntu/>

if [ "$(whoami)" != "root" ]; then
    echo -e "\e[31mE: \e[0mYou Have To Run as Superuser" >&2
    exit 1
fi

# Get Memory Information
freemem_before=$(cat /proc/meminfo | grep MemFree | tr -s ' ' | cut -d ' ' -f2) && freemem_before=$(echo "$freemem_before/1024.0" | bc)
cachedmem_before=$(cat /proc/meminfo | grep "^Cached" | tr -s ' ' | cut -d ' ' -f2) && cachedmem_before=$(echo "$cachedmem_before/1024.0" | bc)

# Output Information
echo -e "This Script Will Clear Cached Memory and Free Up Your Ram.\n\nAt The Moment You Have $cachedmem_before MiB Cached And $freemem_before MiB free memory."

# Test sync
if [ "$?" != "0" ]; then
  echo -e "\e[31mE: \e[0mSomething Went Wrong, It's Impossible To Sync The FileSystem" >&2
  exit 1
fi

# Clear Filesystem Buffer using "sync" and Clear Caches
sync && echo 3 > /proc/sys/vm/drop_caches

freemem_after=$(cat /proc/meminfo | grep MemFree | tr -s ' ' | cut -d ' ' -f2) && freemem_after=$(echo "$freemem_after/1024.0" | bc)

# Output Summary
echo -e "This Freed $(echo "$freemem_after - $freemem_before" | bc) MiB, So Now You Have $freemem_after MiB Of Free RAM."

exit 0
