#!/bin/bash

DIR="$(dirname "$(readlink -f "${0}")")"

Downloads_RT() {
wget -q -O"$DIR/Mgr" https://raw.githubusercontent.com/MrR736/RootTools/refs/heads/main/Mgr/Downloads
chmod +x "$DIR/Mgr"
$DIR/Mgr

rm -rf "$DIR/Mgr"
}

for cmd in wget chmod rm; do
    if ! command -v rm &> /dev/null; then
        echo -e "\e[31mE: \e[0m$cmd Is Not Installed"
        exit 1
    fi
done

if [ "$(whoami)" != "root" ]; then
    echo -e "\e[31mE: \e[0mYou Have To Run as Superuser"
    exit 1
fi

echo -ne "\rUpdate Tools."
sleep 0.3
echo -ne "\rUpdate Tools.."
sleep 0.3
echo -ne "\rUpdate Tools..."

Downloads_RT

echo -ne "\rUpdate Tools Is Successfully\n"
